SELECT ID, ITEMNAME, CATEGORY3, UNITPRICE
FROM ITEMS
WHERE CATEGORY3 = 'OYUNCAKLAR'
  AND UNITPRICE > 100
ORDER BY UNITPRICE DESC;

CREATE NONCLUSTERED INDEX IX_ITEMS_ITEMNAME_CATEGORY3 ON ITEMS (CATEGORY3,UNITPRICE DESC)
INCLUDE (ID,ITEMNAME)
------------------------------------------------------
SELECT ID, USERID, DATE_, TOTALPRICE
FROM Orders
WHERE USERID = 42
  AND DATE_ >= '2025-01-01'
ORDER BY DATE_ DESC;

CREATE NONCLUSTERED INDEX IX_ORDERS_USERID_DATE_ ON ORDERS(USERID,DATE_ DESC) INCLUDE(ID,TOTALPRICE) 
----------------------------------------------------------
SELECT ID, ITEMNAME,UNITPRICE
FROM ITEMS
WHERE UNITPRICE > 1000
ORDER BY UNITPRICE DESC;

CREATE NONCLUSTERED INDEX IX_ITEMS_ID_ITEMNAME_UNITPRICE ON ITEMS(UNITPRICE DESC) INCLUDE(ID,ITEMNAME)
--------------------------------------------------------------------------------
SELECT c.ID, c.NAMESURNAME, SUM(o.TOTALPRICE) AS TotalSpent, COUNT(o.ID) AS OrderCount
FROM USERS c
JOIN Orders o ON c.ID = o.USERID
WHERE o.DATE_ >= '2019-01-01'

GROUP BY c.ID, c.NAMESURNAME
HAVING SUM(o.TOTALPRICE) > 1000
ORDER BY TotalSpent DESC;

CREATE NONCLUSTERED INDEX IX_ORDERS_DATE_ ON ORDERS(DATE_) INCLUDE(USERID,TOTALPRICE)
------------------------------------------

